version: "2"
services:
  portainer:
    image: portainer/portainer
    #restart: never
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
volumes:
  portainer_data: